name: Carbyne
main: code.op.Main
version: 0.3
description: Carbyne weapons and armors.
author: Dolphindalt
commands:
    cg:
        description: Main command. Stands for Carbyne Gear.
    party:
        description: Party commands.
    duel:
        description: Duel commands.
permisions:
    carbyne.admin:
        description: Admin permissions for the entire plugin.
        default: op